version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8099:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager   # optional: remove if you want any node
    volumes:
      - ./html:/usr/share/nginx/html:ro

volumes:
  nginx-html:
    driver: local
